baseURL = 'https://s9game.bet/'
languageCode = 'en-us'
title = 'Download APK'
enableRobotsTXT = true

[taxonomies]  
  about = "about"
  contact = "contact"

[params]
  Description = "Join S9 Game Pakistan and earn money while enjoying thrilling online games. Compete, win, and turn your gaming skills into real rewards. Start earning today!"