baseURL = 'https://hugoblogapp.com'
languageCode = 'en-us'
title = 'Lucky 97 Game'
enableRobotsTXT = true

[taxonomies]  
  about = "about"
  contact = "contact"

[params]
  Description = "The Lucky 97 Game allows players in Pakistan to earn money online, with insights into its unique features, gameplay, and impact on the gaming industry."